### PR TITLE
Unable to parse non-string attributes

### PR DESCRIPTION
**Pull request by SamuelTilly**
Expected behaviour `mq(m('input', {checked: true})).should.have('input[checked=true]')`

### CODE REVIEW

**Comment by SamuelTilly** [comment]
Original tests stopped working after this change but was difficult to debug.

**Comment by SamuelTilly** [comment]
I re-added the olds tests that failed and added a guard against nil values, not sure this is expected behavior but will work much closer to how it did before.

**Comment by StephanHoyer** [comment]
thanks

**Comment by SamuelTilly** [comment]
no problem :), when you have time please create a new patch release

**Pull request merged**
